import Head from 'next/head'
import Cards from '../pages/Cards'
import Design from '../pages/Design.js'

export default function Home() {
  
  const cards = [
    {id: 1, type:'sedans', bcolor:"E28625", content: 'Choose a sedan for its affordability and excellent fuel economy. Ideal for cruising in the city or on your next road trip.'},
    {id: 2, type: 'suvs', bcolor:"006971", content: 'Take an SUV for its spacious interior, power, and versatility. Perfect for your next family vacation and off-road adventures.'},
    {id: 3, type: 'luxury', bcolor:"004140", content: 'Cruise in the best car brands without the bloated prices. Enjoy the enhanced comfort of a luxury rental and arrive in style.'}
  ];
  
  return (
    <div style={{margin:0}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cards cards={cards}/>
      {/* <Design /> */}
    </div>
  )
}
